spring:
   application:
     name: helloserver
   
   
server:
    port: 8071
    
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
     defaultZone: http://localhost:8761/eureka/
  instance:
     hostname: localhost   
    
       
